export default{
    THEME_CHANGE:'THEME_CHANGE',
    THEME_INIT:'THEME_INIT'，
    POPULAR_REFRESH:'POPULAR_REFRESH',
    LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',
    LOAD_POPULAR_SUCCESS:'LOAD_POPULAR_SUCCESS'
}